export const countries = [
  { name: "" },
  { name: "Worldwide" },
  { name: "Algeria" },
  { name: "Argentina" },
  { name: "Australia" },
  { name: "Austria" },
  { name: "Bahrain" },
  { name: "Belgium" },
  { name: "Bolivia" },
  { name: "Brazil" },
  { name: "Canada" },
  { name: "Chile" },
  { name: "Colombia" },
  { name: "Denmark" },
  { name: "Dominican Republic" },
  { name: "Ecuador" },
  { name: "Egypt" },
  { name: "France" },
  { name: "Germany" },
  { name: "Ghana" },
  { name: "Greece" },
  { name: "Guatemala" },
  { name: "India" },
  { name: "Indonesia" },
  { name: "Ireland" },
  { name: "Israel" },
  { name: "Italy" },
  { name: "Japan" },
  { name: "Jordan" },
  { name: "Kenya" },
  { name: "Latvia" },
  { name: "Malaysia" },
  { name: "Mexico" },
  { name: "Netherlands" },
  { name: "New Zealand" },
  { name: "Nigeria" },
  { name: "Norway" },
  { name: "Oman" },
  { name: "Pakistan" },
  { name: "Panama" },
  { name: "Peru" },
  { name: "Philippines" },
  { name: "Poland" },
  { name: "Portugal" },
  { name: "Puerto Rico" },
  { name: "Qatar" },
  { name: "Russia" },
  { name: "Saudi Arabia" },
  { name: "Singapore" },
  { name: "South Africa" },
  { name: "Spain" },
  { name: "Sweden" },
  { name: "Switzerland" },
  { name: "Thailand" },
  { name: "Turkey" },
  { name: "Ukraine" },
  { name: "United Arab Emirates" },
  { name: "United Kingdom" },
  { name: "United States" },
  { name: "Venezuela" },
  { name: "Vietnam" },
];
